---
- hosts: localhost
  connection: local
  become: true
  gather_facts: true
  environment:
    JAVA_HOME: "{{ java_home_path }}"
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_access_secret }}"
  vars_files:
    - "../playbook_vars/vault/test.vault"
  tasks:
    - name: Calling spring boot cloud cli for encryption
      shell: |
          {{ spring_cloud_cli_path | default("") }}spring encrypt {{ user_password }} -key {{ encryption_key }}
      register: reg_encryption_value

    - debug: var=reg_encryption_value
 
    - name: Obtaining aws secret
      shell: "aws secretsmanager describe-secret --secret-id test/ansible_awx  --region eu-west-1"
      register: reg_secrets

    - debug: var=reg_secrets
